### ISSUE TITLE
WARNING when test retrain.py

### ISSUE THREAD

**Issue by ghaidaahmed** [priyanshugandhi/priyanshu-face_recognition#1]
dear Mr.priyanshugandhi,
I have a problem ,when I run   `python retrain.py --output_graph=retrained_graph.pb --output_labels=retrained_labels.txt --architecture=inception_v3 --image_dir=images` in termnal show me warning below and no added these files retrained_graph.pb and retrained_labels.txt .

@priyanshugandhi
`WARNING:tensorflow:From /Users/ghaida/Downloads/priyanshu-face_recognition-master/retrain.py:274: __init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
2019-04-05 21:46:13.570350: W tensorflow/core/framework/op_def_util.cc:355] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
ERROR:tensorflow:Image directory 'images' not found.
Traceback (most recent call last):
  File "/Users/ghaida/Downloads/priyanshu-face_recognition-master/retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/ghaida/Downloads/priyanshu-face_recognition-master/retrain.py", line 989, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys`

do you know what is the problem, I want the project run and test it before Saturday (GMT)

**Comment by priyanshugandhi** [comment]
You need to maintain an images directory holding the dataset.

**Comment by priyanshugandhi** [comment]
Closed
